language: go

go:
- "1.13"
- "1.12"

# Only clone the most recent commit.
git:
  depth: 1

jobs:
  include:
    - stage: verify
      install:
        - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.17.1
      script:
        - ./bin/golangci-lint run # run a bunch of code checkers/linters in parallel
        - go test -v -race ./...  # Run all the tests with the race detector enabled
