language: go

go:
- "1.13"
- "1.12"

# Only clone the most recent commit.
git:
  depth: 1

jobs:
  include:
    - stage: source check

      install:
        - GO111MODULE=off go get gopkg.in/golangci/golangci-lint.v1/cmd/golangci-lint

      script:
        - go build ./...
        - golangci-lint run # run a bunch of code checkers/linters in parallel
        - go test -v -race ./...  # Run all the tests with the race detector enabled
