# branch: semrel

branches:
  - master
  - name: develop
    prerelease: dev
  - name: docker-image
    prerelease: docker-image

tagFormat: v${version}

plugins:
  - - "@semantic-release/commit-analyzer"
    # - releaseRules:
    #  - type: "fix"
    #    release: "prerelease"
  - - "@semantic-release/exec"
    - prepareCmd: './gen-build.sh "${nextRelease.version}" "${options.branch}" "${commits.length}" "${(new Date()).toISOString()}"'
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: docs/CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - "docs/CHANGELOG.md"
  - - "@semantic-release/github"
    - assets:
      - path: "../../../bin/gofind"
        label: false
